#ifndef MISSION_VERSIONDEFINES_HPP
#define MISSION_VERSIONDEFINES_HPP

/////////////////////////////////////////////////////////////////////////////
// This file is generated by CMake with macro 'generate_version_header'
// Do not modify directly.
/////////////////////////////////////////////////////////////////////////////

// Preprocessor definitions providing compile-time access to version information

#define MISSION_VERSION_MAJOR        2
#define MISSION_VERSION_MINOR        7
#define MISSION_VERSION_PATCH        1
#define MISSION_VERSION              "2.7.1"
#define MISSION_RELEASE_VERSION      "2.7.1 11-19-2020"

// Miscellaneous preprocessor definitions for use by resource files

#define MISSION_FILEVERSION          MISSION_VERSION_MAJOR,MISSION_VERSION_MINOR,MISSION_VERSION_PATCH
#define MISSION_FILEVERSION_STR      MISSION_VERSION
#define MISSION_PRODUCTVERSION       MISSION_FILEVERSION
#define MISSION_PRODUCTVERSION_STR   MISSION_RELEASE_VERSION

#define MISSION_COMPANYNAME_STR      "United States Air Force (USAF)"
#define MISSION_LEGALCOPYRIGHT_STR   "Multiple"
#define MISSION_LEGALTRADEMARKS1_STR "All Rights Reserved"
#define MISSION_LEGALTRADEMARKS2_STR MISSION_LEGALTRADEMARKS1_STR
#define MISSION_COMPANYDOMAIN_STR    "https://airforce.com"

// Application specific preprocessor definitions used by resource files

#define MISSION_FILEDESCRIPTION_STR  "AFSIM's mission simulation tool"
//#define MISSION_INTERNALNAME_STR   "TBD"
#define MISSION_ORIGINALFILENAME_STR "mission.exe"
#define MISSION_PRODUCTNAME_STR      "AFSIM-Mission"

#endif
