#ifndef MYSTIC_VERSIONDEFINES_HPP
#define MYSTIC_VERSIONDEFINES_HPP

/////////////////////////////////////////////////////////////////////////////
// This file is generated by CMake with macro 'generate_version_header'
// Do not modify directly.
/////////////////////////////////////////////////////////////////////////////

// Preprocessor definitions providing compile-time access to version information

#define MYSTIC_VERSION_MAJOR        2
#define MYSTIC_VERSION_MINOR        7
#define MYSTIC_VERSION_PATCH        1
#define MYSTIC_VERSION              "2.7.1"
#define MYSTIC_RELEASE_VERSION      "2.7.1 11-19-2020"

// Miscellaneous preprocessor definitions for use by resource files

#define MYSTIC_FILEVERSION          MYSTIC_VERSION_MAJOR,MYSTIC_VERSION_MINOR,MYSTIC_VERSION_PATCH
#define MYSTIC_FILEVERSION_STR      MYSTIC_VERSION
#define MYSTIC_PRODUCTVERSION       MYSTIC_FILEVERSION
#define MYSTIC_PRODUCTVERSION_STR   MYSTIC_RELEASE_VERSION

#define MYSTIC_COMPANYNAME_STR      "United States Air Force (USAF)"
#define MYSTIC_LEGALCOPYRIGHT_STR   "Multiple"
#define MYSTIC_LEGALTRADEMARKS1_STR "All Rights Reserved"
#define MYSTIC_LEGALTRADEMARKS2_STR MYSTIC_LEGALTRADEMARKS1_STR
#define MYSTIC_COMPANYDOMAIN_STR    "https://airforce.com"

// Application specific preprocessor definitions used by resource files

#define MYSTIC_FILEDESCRIPTION_STR  "AFSIM's application for the visualization of event_pipe output"
//#define MYSTIC_INTERNALNAME_STR   "TBD"
#define MYSTIC_ORIGINALFILENAME_STR "mystic.exe"
#define MYSTIC_PRODUCTNAME_STR      "AFSIM-Mystic"

#endif
