#ifndef WSF_VERSIONDEFINES_HPP
#define WSF_VERSIONDEFINES_HPP

/////////////////////////////////////////////////////////////////////////////
// This file is generated by CMake with macro 'generate_version_header'
// Do not modify directly.
/////////////////////////////////////////////////////////////////////////////

// Preprocessor definitions providing compile-time access to version information

#define WSF_VERSION_MAJOR        2
#define WSF_VERSION_MINOR        7
#define WSF_VERSION_PATCH        1
#define WSF_VERSION              "2.7.1"
#define WSF_RELEASE_VERSION      "2.7.1 11-19-2020"

// Miscellaneous preprocessor definitions for use by resource files

#define WSF_FILEVERSION          WSF_VERSION_MAJOR,WSF_VERSION_MINOR,WSF_VERSION_PATCH
#define WSF_FILEVERSION_STR      WSF_VERSION
#define WSF_PRODUCTVERSION       WSF_FILEVERSION
#define WSF_PRODUCTVERSION_STR   WSF_RELEASE_VERSION

#define WSF_COMPANYNAME_STR      "United States Air Force (USAF)"
#define WSF_LEGALCOPYRIGHT_STR   "Multiple"
#define WSF_LEGALTRADEMARKS1_STR "All Rights Reserved"
#define WSF_LEGALTRADEMARKS2_STR WSF_LEGALTRADEMARKS1_STR
#define WSF_COMPANYDOMAIN_STR    "https://airforce.com"

// Application specific preprocessor definitions used by resource files

#define WSF_FILEDESCRIPTION_STR  
//#define WSF_INTERNALNAME_STR   
#define WSF_ORIGINALFILENAME_STR 
#define WSF_PRODUCTNAME_STR      

#endif
